export type Profile =
  "João Catalão" | "Vítor" | "Armazém" | "Gerência" | "Campo";
export type Source = "ACRS" | "demo";
export type Ref = { file: string; sheet?: string; row?: number };
export type Work = {
  id: string;
  numero: string;
  nome: string;
  local: string | null;
  cliente: string;
  estado: string;
  dataInicio?: string;
  dataFim?: string | null;
  source: Source;
};
export type Article = {
  id: string;
  codigoACRS: string;
  familia: string;
  material: string | null;
  tamanho: string | null;
  descricao: string;
  marca: string | null;
  quantidade: number;
  precoUnitario: number;
  precoTotal: number;
  localizacao: string | null;
  unidade?: string;
  precisao?: number;
  unidadeSource?: "demo";
  source: Source;
  sourcePage?: number;
  sourceRow?: number;
};
export type Person = {
  id: string;
  nome: string;
  custoHora: number | null;
  horasDia: number | null;
  empresaId: string | null;
  tipo: string | null;
  source: Source;
};
export type Company = {
  id: string;
  nome: string;
  tipo: "Interna" | "Subcontratada";
  source: Source;
};
export type TimeEntry = {
  id: string;
  pessoaId: string;
  nome: string;
  data: string;
  obraId: string;
  local: string | null;
  entradaManha: string | null;
  saidaManha: string | null;
  entradaTarde: string | null;
  saidaTarde: string | null;
  entradaNoite: string | null;
  saidaNoite: string | null;
  tempoViagem: string | null;
  horas: number;
  horasViagem: number;
  horasNoturnas: number;
  horasExtraExcel: number;
  source: Source;
  sourceRef?: Ref;
  registadoEm?: string;
  utilizador?: string;
};
export type Invoice = {
  id: string;
  data: string;
  fornecedor: string;
  nifFornecedor?: string;
  numero: string;
  obraId: string;
  categoria: string | null;
  valor: number;
  source: Source;
  sourceRef?: Ref;
  estado: "Rascunho" | "Por validar" | "Validada" | "Rejeitada";
  tipo: "Despesa de obra" | "Compra para stock";
  documento?: string;
  artigoId?: string;
  quantidade?: number;
  registadoEm?: string;
  utilizador?: string;
  validadoEm?: string;
  validadoPor?: string;
  rejeitadoEm?: string;
  rejeitadoPor?: string;
  ocrStatus?: "PENDING" | "PROCESSING" | "NEEDS_REVIEW" | "CONFIRMED" | "OCR_FAILED" | "MANUAL";
  ocrConfidence?: number;
  ocrRaw?: any;
  items?: InvoiceItem[];
};
export type InvoiceItem = {
  id?: string;
  invoiceId?: string;
  descricao: string;
  quantidade: number;
  precoUnitario: number;
  subtotal: number;
  ivaTaxa?: number;
  artigoId?: string;
};
export type OCRResult = {
  fornecedor?: string;
  nifFornecedor?: string;
  categoria?: string;
  numero?: string;
  data?: string;
  valorTotal?: number;
  valorSemIva?: number;
  ivaValor?: number;
  ivaTaxa?: number;
  confidence?: number;
  linhas?: Array<{
    descricao: string;
    quantidade: number;
    precoUnitario: number;
    subtotal: number;
  }>;
  rawText?: string;
  documentUrl?: string;
};
export type Movement = {
  id: string;
  tipo: "Saída" | "Devolução" | "Entrada" | "Outro";
  artigoId: string;
  obraId: string;
  descricao: string;
  quantidade: number;
  valorUnitario: number;
  data: string;
  registadoEm: string;
  utilizador: string;
  source: Source;
  origemId?: string;
  totalNaSaida?: boolean;
  fornecedor?: string;
};
export type Machine = {
  id: string;
  numero: string;
  nome: string;
  marca: string;
  modelo: string;
  estado: string;
  custoDia: number;
  custoInternoDia?: number;
  custoAquisicao?: number;
  manutencaoAcumulada?: number;
  tipo: "Máquina" | "Caixa";
  source: Source;
};
export type Allocation = {
  id: string;
  maquinaId: string;
  obraId: string;
  saida: string;
  devolucao: string | null;
  custoDia: number;
  utilizador: string;
  registadoEm: string;
  source: Source;
};
export type Budget = {
  obraId: string;
  valor: number;
  margem: number;
  modo: string;
  linhas: { categoria: string; valor: number }[];
  source: Source;
};
export type Policy = {
  limiteExtra: number;
  extra: number;
  noturno: number;
  sabado: number;
  domingo: number;
  feriado: number;
  acumular: boolean;
  source: "demo";
};
export type Settings = {
  minimos: Record<string, number>;
  valoresInternos: Record<string, number>;
  policy: Policy;
  personPolicies: Record<string, Partial<Policy>>;
  companyPolicies: Record<string, Partial<Policy>>;
  holidays: string[];
};
export type Cost = {
  id: string;
  obraId: string;
  data: string;
  registadoEm: string;
  origem: string;
  origemId: string;
  descricao: string;
  categoria: string;
  quantidade: number;
  valorUnitario: number;
  valor: number;
  utilizador: string;
  source: Source;
  sourceRef?: Ref;
  pessoaId?: string;
  nota?: string;
};
export type State = {
  works: Work[];
  articles: Article[];
  people: Person[];
  companies: Company[];
  times: TimeEntry[];
  invoices: Invoice[];
  movements: Movement[];
  machines: Machine[];
  allocations: Allocation[];
  budgets: Budget[];
  settings: Settings;
  manualCosts: Cost[];
};
